// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Command.proto
// Protobuf Java Version: 4.28.0

package cn.gsq.host.common.protobuf;

public final class Command {
  private Command() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      Command.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * *
   * 指令类型
   * </pre>
   *
   * Protobuf enum {@code cn.gsq.host.common.protobuf.CommandType}
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * *
     * 身份认证
     * </pre>
     *
     * <code>AUTH = 0;</code>
     */
    AUTH(0),
    /**
     * <pre>
     * *
     * 认证响应
     * </pre>
     *
     * <code>AUTH_BACK = 1;</code>
     */
    AUTH_BACK(1),
    /**
     * <pre>
     * *
     * 心跳
     * </pre>
     *
     * <code>PING = 2;</code>
     */
    PING(2),
    /**
     * <pre>
     * *
     * 心跳响应
     * </pre>
     *
     * <code>PONG = 3;</code>
     */
    PONG(3),
    /**
     * <pre>
     * *
     * 推送数据
     * </pre>
     *
     * <code>PUSH = 4;</code>
     */
    PUSH(4),
    /**
     * <pre>
     * *
     * 推送响应
     * </pre>
     *
     * <code>PUSH_BACK = 5;</code>
     */
    PUSH_BACK(5),
    /**
     * <pre>
     * *
     * 拉取数据
     * </pre>
     *
     * <code>PULL = 6;</code>
     */
    PULL(6),
    /**
     * <pre>
     * *
     * 拉取响应
     * </pre>
     *
     * <code>PULL_BACK = 7;</code>
     */
    PULL_BACK(7),
    /**
     * <pre>
     * *
     * 主机退役
     * </pre>
     *
     * <code>RESIGN = 8;</code>
     */
    RESIGN(8),
    /**
     * <pre>
     * *
     * 退役响应
     * </pre>
     *
     * <code>RESIGN_BACK = 9;</code>
     */
    RESIGN_BACK(9),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "",
        CommandType.class.getName());
    }
    /**
     * <pre>
     * *
     * 身份认证
     * </pre>
     *
     * <code>AUTH = 0;</code>
     */
    public static final int AUTH_VALUE = 0;
    /**
     * <pre>
     * *
     * 认证响应
     * </pre>
     *
     * <code>AUTH_BACK = 1;</code>
     */
    public static final int AUTH_BACK_VALUE = 1;
    /**
     * <pre>
     * *
     * 心跳
     * </pre>
     *
     * <code>PING = 2;</code>
     */
    public static final int PING_VALUE = 2;
    /**
     * <pre>
     * *
     * 心跳响应
     * </pre>
     *
     * <code>PONG = 3;</code>
     */
    public static final int PONG_VALUE = 3;
    /**
     * <pre>
     * *
     * 推送数据
     * </pre>
     *
     * <code>PUSH = 4;</code>
     */
    public static final int PUSH_VALUE = 4;
    /**
     * <pre>
     * *
     * 推送响应
     * </pre>
     *
     * <code>PUSH_BACK = 5;</code>
     */
    public static final int PUSH_BACK_VALUE = 5;
    /**
     * <pre>
     * *
     * 拉取数据
     * </pre>
     *
     * <code>PULL = 6;</code>
     */
    public static final int PULL_VALUE = 6;
    /**
     * <pre>
     * *
     * 拉取响应
     * </pre>
     *
     * <code>PULL_BACK = 7;</code>
     */
    public static final int PULL_BACK_VALUE = 7;
    /**
     * <pre>
     * *
     * 主机退役
     * </pre>
     *
     * <code>RESIGN = 8;</code>
     */
    public static final int RESIGN_VALUE = 8;
    /**
     * <pre>
     * *
     * 退役响应
     * </pre>
     *
     * <code>RESIGN_BACK = 9;</code>
     */
    public static final int RESIGN_BACK_VALUE = 9;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CommandType forNumber(int value) {
      switch (value) {
        case 0: return AUTH;
        case 1: return AUTH_BACK;
        case 2: return PING;
        case 3: return PONG;
        case 4: return PUSH;
        case 5: return PUSH_BACK;
        case 6: return PULL;
        case 7: return PULL_BACK;
        case 8: return RESIGN;
        case 9: return RESIGN_BACK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CommandType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.gsq.host.common.protobuf.Command.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CommandType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cn.gsq.host.common.protobuf.CommandType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCommand.proto\022\033cn.gsq.host.common.prot" +
      "obuf*\211\001\n\013CommandType\022\010\n\004AUTH\020\000\022\r\n\tAUTH_B" +
      "ACK\020\001\022\010\n\004PING\020\002\022\010\n\004PONG\020\003\022\010\n\004PUSH\020\004\022\r\n\tP" +
      "USH_BACK\020\005\022\010\n\004PULL\020\006\022\r\n\tPULL_BACK\020\007\022\n\n\006R" +
      "ESIGN\020\010\022\017\n\013RESIGN_BACK\020\tB\013B\007CommandP\000b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
