// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Message.proto
// Protobuf Java Version: 4.28.0

package cn.gsq.host.common.protobuf;

public final class Message {
  private Message() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      Message.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.gsq.host.common.protobuf.BaseMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * *
     * 客户端唯一标识
     * </pre>
     *
     * <code>string clientId = 1;</code>
     * @return The clientId.
     */
    java.lang.String getClientId();
    /**
     * <pre>
     * *
     * 客户端唯一标识
     * </pre>
     *
     * <code>string clientId = 1;</code>
     * @return The bytes for clientId.
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <pre>
     * *
     * 指令类型
     * </pre>
     *
     * <code>.cn.gsq.host.common.protobuf.CommandType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     * *
     * 指令类型
     * </pre>
     *
     * <code>.cn.gsq.host.common.protobuf.CommandType type = 2;</code>
     * @return The type.
     */
    cn.gsq.host.common.protobuf.Command.CommandType getType();

    /**
     * <pre>
     * *
     * 指令包
     * </pre>
     *
     * <code>optional string data = 3;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <pre>
     * *
     * 指令包
     * </pre>
     *
     * <code>optional string data = 3;</code>
     * @return The data.
     */
    java.lang.String getData();
    /**
     * <pre>
     * *
     * 指令包
     * </pre>
     *
     * <code>optional string data = 3;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <pre>
     * *
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 4;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <pre>
     * *
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 4;</code>
     * @return The time.
     */
    com.google.protobuf.Timestamp getTime();
    /**
     * <pre>
     * *
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();
  }
  /**
   * Protobuf type {@code cn.gsq.host.common.protobuf.BaseMsg}
   */
  public static final class BaseMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cn.gsq.host.common.protobuf.BaseMsg)
      BaseMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "",
        BaseMsg.class.getName());
    }
    // Use BaseMsg.newBuilder() to construct.
    private BaseMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BaseMsg() {
      clientId_ = "";
      type_ = 0;
      data_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.gsq.host.common.protobuf.Message.internal_static_cn_gsq_host_common_protobuf_BaseMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.gsq.host.common.protobuf.Message.internal_static_cn_gsq_host_common_protobuf_BaseMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.gsq.host.common.protobuf.Message.BaseMsg.class, cn.gsq.host.common.protobuf.Message.BaseMsg.Builder.class);
    }

    private int bitField0_;
    public static final int CLIENTID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object clientId_ = "";
    /**
     * <pre>
     * *
     * 客户端唯一标识
     * </pre>
     *
     * <code>string clientId = 1;</code>
     * @return The clientId.
     */
    @java.lang.Override
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * *
     * 客户端唯一标识
     * </pre>
     *
     * <code>string clientId = 1;</code>
     * @return The bytes for clientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_ = 0;
    /**
     * <pre>
     * *
     * 指令类型
     * </pre>
     *
     * <code>.cn.gsq.host.common.protobuf.CommandType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * *
     * 指令类型
     * </pre>
     *
     * <code>.cn.gsq.host.common.protobuf.CommandType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public cn.gsq.host.common.protobuf.Command.CommandType getType() {
      cn.gsq.host.common.protobuf.Command.CommandType result = cn.gsq.host.common.protobuf.Command.CommandType.forNumber(type_);
      return result == null ? cn.gsq.host.common.protobuf.Command.CommandType.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object data_ = "";
    /**
     * <pre>
     * *
     * 指令包
     * </pre>
     *
     * <code>optional string data = 3;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * *
     * 指令包
     * </pre>
     *
     * <code>optional string data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * *
     * 指令包
     * </pre>
     *
     * <code>optional string data = 3;</code>
     * @return The bytes for data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp time_;
    /**
     * <pre>
     * *
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 4;</code>
     * @return Whether the time field is set.
     */
    @java.lang.Override
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * *
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 4;</code>
     * @return The time.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTime() {
      return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
    }
    /**
     * <pre>
     * *
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
      return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, clientId_);
      }
      if (type_ != cn.gsq.host.common.protobuf.Command.CommandType.AUTH.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, data_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(4, getTime());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, clientId_);
      }
      if (type_ != cn.gsq.host.common.protobuf.Command.CommandType.AUTH.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, data_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getTime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.gsq.host.common.protobuf.Message.BaseMsg)) {
        return super.equals(obj);
      }
      cn.gsq.host.common.protobuf.Message.BaseMsg other = (cn.gsq.host.common.protobuf.Message.BaseMsg) obj;

      if (!getClientId()
          .equals(other.getClientId())) return false;
      if (type_ != other.type_) return false;
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (!getTime()
            .equals(other.getTime())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.gsq.host.common.protobuf.Message.BaseMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gsq.host.common.protobuf.Message.BaseMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gsq.host.common.protobuf.Message.BaseMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gsq.host.common.protobuf.Message.BaseMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gsq.host.common.protobuf.Message.BaseMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gsq.host.common.protobuf.Message.BaseMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gsq.host.common.protobuf.Message.BaseMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.gsq.host.common.protobuf.Message.BaseMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.gsq.host.common.protobuf.Message.BaseMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.gsq.host.common.protobuf.Message.BaseMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.gsq.host.common.protobuf.Message.BaseMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.gsq.host.common.protobuf.Message.BaseMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.gsq.host.common.protobuf.Message.BaseMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.gsq.host.common.protobuf.BaseMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.gsq.host.common.protobuf.BaseMsg)
        cn.gsq.host.common.protobuf.Message.BaseMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.gsq.host.common.protobuf.Message.internal_static_cn_gsq_host_common_protobuf_BaseMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.gsq.host.common.protobuf.Message.internal_static_cn_gsq_host_common_protobuf_BaseMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.gsq.host.common.protobuf.Message.BaseMsg.class, cn.gsq.host.common.protobuf.Message.BaseMsg.Builder.class);
      }

      // Construct using cn.gsq.host.common.protobuf.Message.BaseMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getTimeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        clientId_ = "";
        type_ = 0;
        data_ = "";
        time_ = null;
        if (timeBuilder_ != null) {
          timeBuilder_.dispose();
          timeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.gsq.host.common.protobuf.Message.internal_static_cn_gsq_host_common_protobuf_BaseMsg_descriptor;
      }

      @java.lang.Override
      public cn.gsq.host.common.protobuf.Message.BaseMsg getDefaultInstanceForType() {
        return cn.gsq.host.common.protobuf.Message.BaseMsg.getDefaultInstance();
      }

      @java.lang.Override
      public cn.gsq.host.common.protobuf.Message.BaseMsg build() {
        cn.gsq.host.common.protobuf.Message.BaseMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.gsq.host.common.protobuf.Message.BaseMsg buildPartial() {
        cn.gsq.host.common.protobuf.Message.BaseMsg result = new cn.gsq.host.common.protobuf.Message.BaseMsg(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cn.gsq.host.common.protobuf.Message.BaseMsg result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.clientId_ = clientId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.type_ = type_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.data_ = data_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.time_ = timeBuilder_ == null
              ? time_
              : timeBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.gsq.host.common.protobuf.Message.BaseMsg) {
          return mergeFrom((cn.gsq.host.common.protobuf.Message.BaseMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.gsq.host.common.protobuf.Message.BaseMsg other) {
        if (other == cn.gsq.host.common.protobuf.Message.BaseMsg.getDefaultInstance()) return this;
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasData()) {
          data_ = other.data_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasTime()) {
          mergeTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                clientId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                data_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object clientId_ = "";
      /**
       * <pre>
       * *
       * 客户端唯一标识
       * </pre>
       *
       * <code>string clientId = 1;</code>
       * @return The clientId.
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * *
       * 客户端唯一标识
       * </pre>
       *
       * <code>string clientId = 1;</code>
       * @return The bytes for clientId.
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * *
       * 客户端唯一标识
       * </pre>
       *
       * <code>string clientId = 1;</code>
       * @param value The clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        clientId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * *
       * 客户端唯一标识
       * </pre>
       *
       * <code>string clientId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientId() {
        clientId_ = getDefaultInstance().getClientId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * *
       * 客户端唯一标识
       * </pre>
       *
       * <code>string clientId = 1;</code>
       * @param value The bytes for clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        clientId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * *
       * 指令类型
       * </pre>
       *
       * <code>.cn.gsq.host.common.protobuf.CommandType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * *
       * 指令类型
       * </pre>
       *
       * <code>.cn.gsq.host.common.protobuf.CommandType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * *
       * 指令类型
       * </pre>
       *
       * <code>.cn.gsq.host.common.protobuf.CommandType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public cn.gsq.host.common.protobuf.Command.CommandType getType() {
        cn.gsq.host.common.protobuf.Command.CommandType result = cn.gsq.host.common.protobuf.Command.CommandType.forNumber(type_);
        return result == null ? cn.gsq.host.common.protobuf.Command.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * *
       * 指令类型
       * </pre>
       *
       * <code>.cn.gsq.host.common.protobuf.CommandType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(cn.gsq.host.common.protobuf.Command.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * *
       * 指令类型
       * </pre>
       *
       * <code>.cn.gsq.host.common.protobuf.CommandType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <pre>
       * *
       * 指令包
       * </pre>
       *
       * <code>optional string data = 3;</code>
       * @return Whether the data field is set.
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * *
       * 指令包
       * </pre>
       *
       * <code>optional string data = 3;</code>
       * @return The data.
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * *
       * 指令包
       * </pre>
       *
       * <code>optional string data = 3;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * *
       * 指令包
       * </pre>
       *
       * <code>optional string data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * *
       * 指令包
       * </pre>
       *
       * <code>optional string data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = getDefaultInstance().getData();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * *
       * 指令包
       * </pre>
       *
       * <code>optional string data = 3;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        data_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp time_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeBuilder_;
      /**
       * <pre>
       * *
       * 时间戳
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 4;</code>
       * @return Whether the time field is set.
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * *
       * 时间戳
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 4;</code>
       * @return The time.
       */
      public com.google.protobuf.Timestamp getTime() {
        if (timeBuilder_ == null) {
          return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        } else {
          return timeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * *
       * 时间戳
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      public Builder setTime(com.google.protobuf.Timestamp value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          time_ = value;
        } else {
          timeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * *
       * 时间戳
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      public Builder setTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timeBuilder_ == null) {
          time_ = builderForValue.build();
        } else {
          timeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * *
       * 时间戳
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      public Builder mergeTime(com.google.protobuf.Timestamp value) {
        if (timeBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            time_ != null &&
            time_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getTimeBuilder().mergeFrom(value);
          } else {
            time_ = value;
          }
        } else {
          timeBuilder_.mergeFrom(value);
        }
        if (time_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * *
       * 时间戳
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        time_ = null;
        if (timeBuilder_ != null) {
          timeBuilder_.dispose();
          timeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * *
       * 时间戳
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimeBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getTimeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * *
       * 时间戳
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilder();
        } else {
          return time_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        }
      }
      /**
       * <pre>
       * *
       * 时间戳
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTime(),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:cn.gsq.host.common.protobuf.BaseMsg)
    }

    // @@protoc_insertion_point(class_scope:cn.gsq.host.common.protobuf.BaseMsg)
    private static final cn.gsq.host.common.protobuf.Message.BaseMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.gsq.host.common.protobuf.Message.BaseMsg();
    }

    public static cn.gsq.host.common.protobuf.Message.BaseMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMsg>
        PARSER = new com.google.protobuf.AbstractParser<BaseMsg>() {
      @java.lang.Override
      public BaseMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BaseMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.gsq.host.common.protobuf.Message.BaseMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gsq_host_common_protobuf_BaseMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_gsq_host_common_protobuf_BaseMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\033cn.gsq.host.common.prot" +
      "obuf\032\037google/protobuf/timestamp.proto\032\rC" +
      "ommand.proto\"\231\001\n\007BaseMsg\022\020\n\010clientId\030\001 \001" +
      "(\t\0226\n\004type\030\002 \001(\0162(.cn.gsq.host.common.pr" +
      "otobuf.CommandType\022\021\n\004data\030\003 \001(\tH\000\210\001\001\022(\n" +
      "\004time\030\004 \001(\0132\032.google.protobuf.TimestampB" +
      "\007\n\005_dataB\013B\007MessageP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          cn.gsq.host.common.protobuf.Command.getDescriptor(),
        });
    internal_static_cn_gsq_host_common_protobuf_BaseMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_gsq_host_common_protobuf_BaseMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cn_gsq_host_common_protobuf_BaseMsg_descriptor,
        new java.lang.String[] { "ClientId", "Type", "Data", "Time", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    cn.gsq.host.common.protobuf.Command.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
